[package]
name = "Calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3" }
anyhow = "1.0.100"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
